name: Build and deploy to dev

permissions:
  contents: read

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
    branches:
      - 'main'
      - 'develop'

# Cancel any existing runs of this workflow on the same branch/pr
# We always want to build/deploy/test a new commit over an older one
concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true

jobs:

  # Start running unit tests early - we want to run them always
  # and they don't depend on build or deployment

  # Looks for labels like "deploy-to-<env>" attached to a PR so we can deploy to those envs
  get-deploy-labels:
    name: Get Deploy Envs
    runs-on: ubuntu-latest
    outputs:
      deploy-envs: ${{ steps.get-labels.outputs.deploy-envs }}
    steps:
      - id: get-labels
        uses: mindsdb/github-actions/get-deploy-labels@main

  # This will run the deployment workflow in the base branch, not in the PR.
  # So if you change the deploy workflow in your PR, the changes won't be reflected in this run.
  deploy:
    if: ${{needs.get-deploy-labels.outputs.deploy-envs != '[]' }}
    name: Deploy
    uses: ./.github/workflows/deploy.yml
    with:
      deploy-envs: '["dev"]'
      image-tag: ${{ github.event.pull_request.head.sha }}
    secrets: inherit
